spring.application.name=notification-service
#Kafka Consumer properties

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notificationService
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

#spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=io.confluent.kafka.serializers.KafkaAvroDeserializer

# Trusted Packages
# This allows Kafka to convert JSON into classes within this package
spring.kafka.consumer.properties.spring.json.trusted.packages=com.ecom.notification.order

# Optional: Type Mapping
# Use this if the producer uses a different package name for OrderPlacedEvent
spring.kafka.consumer.properties.spring.json.value.default.type=com.ecom.notification.order.OrderPlacedEvent

