spring.application.name=order-service
spring.datasource.url=jdbc:mysql://localhost:3306/order_service
spring.datasource.username=root
spring.datasource.password=mysql

#this is normally disabled in real env with value as none
spring.jpa.hibernate.ddl-auto=none

server.port=8081

#Kafka properties
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.template.default-topic=order-placed
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#deprecated need to find a replacement
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

