spring.application.name=product-service

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=product-service

#spring.data.mongodb.uri=mongodb://localhost:27017/product-service
